---
mcpServers:
  filesystem:
    transport: stdio
    command: npx
    args: ["-y", "@modelcontextprotocol/server-filesystem", "./cuga_workspace"]
    description: Local file system operations via MCP

  github:
    transport: stdio
    command: npx
    args: ["-y", "@modelcontextprotocol/server-github"]
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_TOKEN}"
    description: GitHub MCP server (requires GITHUB_TOKEN)

services:
  - digital_sales:
      url: "${DIGITAL_SALES_OPENAPI_URL:-https://digitalsales.19pc1vtv090u.us-east.codeengine.appdomain.cloud/openapi.json}"
      description: Example OpenAPI service (Digital Sales)
